apiVersion: skaffold/v2beta9
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  artifacts:
    - image: jlmonteagudo/auth
      context: .
      docker:
        dockerfile: ./infra/docker/auth.Dockerfile
      sync:
        manual:
          - src: './apps/backend/auth/src/**/*.ts'
            dest: .
